const products={eagle:{name:'1 oz American Gold Eagle',spot:3000,premium:0.052},maple:{name:'1 oz Canadian Gold Maple Leaf',spot:3000,premium:0.038},bar:{name:'1 oz Gold Bar',spot:3000,premium:0.025},silver:{name:'1 oz American Silver Eagle',spot:30,premium:0.16}};
const dealers=[
{name:'Founding Dealer',location:'Midtown Manhattan · Local pickup',rating:4.9,reviews:184,adjustment:0,ship:0,time:0,payment:0,local:true},
{name:'Liberty Bullion',location:'Online dealer · Insured shipping',rating:4.8,reviews:972,adjustment:-0.006,ship:24.95,time:3,payment:0,local:false},
{name:'Atlantic Metals',location:'Online dealer · Insured shipping',rating:4.7,reviews:624,adjustment:0.004,ship:0,time:5,payment:18,local:false}
];
let mode='buy';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
function getOffers(){const p=products[product.value];const qty=Math.max(1,Number(quantity.value)||1);return dealers.map(d=>{const unit=mode==='buy'?p.spot*(1+p.premium+d.adjustment):p.spot*(.965+d.adjustment);const total=mode==='buy'?unit*qty+d.ship+d.payment:unit*qty;return {...d,unit,total,qty,premium:mode==='buy'?(unit/p.spot-1)*100:(unit/p.spot)*100}})}
function render(){let offers=getOffers();const sort=sortSelect.value;if(sort==='best')offers.sort((a,b)=>mode==='buy'?a.total-b.total:b.total-a.total);if(sort==='fast')offers.sort((a,b)=>a.time-b.time);if(sort==='rating')offers.sort((a,b)=>b.rating-a.rating);resultsTitle.textContent=mode==='buy'?'Best prices to buy':'Best offers to sell';resultCount.textContent=`${offers.length} offers`;spotPrice.textContent=`${money(products[product.value].spot)} / oz`;results.innerHTML=offers.map((o,i)=>`<article class="offer ${i===0?'best':''}">${i===0?'<span class="best-badge">Best match</span>':''}<div><div class="dealer-name">${o.name}</div><span class="dealer-meta">${o.location}</span><span class="rating">★ ${o.rating} <span class="dealer-meta" style="display:inline">(${o.reviews})</span></span></div><div><span class="cell-label">${mode==='buy'?'Price per unit':'Estimated per unit'}</span><strong>${money(o.unit)}</strong><span class="dealer-meta">${mode==='buy'?o.premium.toFixed(1)+'% premium':o.premium.toFixed(1)+'% of spot'}</span></div><div><span class="cell-label">${mode==='buy'?'Shipping / pickup':'Appraisal'}</span><strong>${o.local?'Free pickup':o.ship?money(o.ship):'Free'}</strong><span class="dealer-meta">${o.local?'Same day':o.time+'–'+(o.time+2)+' days'}</span></div><div class="total"><span class="cell-label">${mode==='buy'?'Estimated total':'Estimated payout'}</span><strong>${money(o.total)}</strong><span class="dealer-meta">For ${o.qty} item${o.qty>1?'s':''}</span></div><button data-dealer="${o.name}">${mode==='buy'?'Reserve':'Request quote'}</button></article>`).join('');document.querySelectorAll('[data-dealer]').forEach(b=>b.onclick=()=>openTransaction(b.dataset.dealer));}
function openTransaction(dealer){const p=products[product.value];modalContent.innerHTML=`<h2 class="modal-title">${mode==='buy'?'Reserve with':'Request an appraisal from'} ${dealer}</h2><p class="modal-copy">${mode==='buy'?`Reserve ${quantity.value} × ${p.name}. The dealer will confirm inventory and final price before payment.`:`Receive a conditional estimate for ${quantity.value} × ${p.name}, then confirm after in-person authentication.`}</p><form class="modal-form"><input required placeholder="Full name"><input required type="email" placeholder="Email address"><input required placeholder="Mobile number"><button class="primary-btn" style="padding:14px">Continue request</button></form>`;modalContent.querySelector('form').onsubmit=e=>{e.preventDefault();modalContent.innerHTML='<div class="success">✓ Prototype request captured. No information was sent or stored.</div>'};actionModal.showModal();}
document.querySelectorAll('.mode').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));btn.classList.add('active');mode=btn.dataset.mode;render()});[product,quantity,sortSelect].forEach(el=>el.addEventListener('change',render));compareBtn.onclick=render;document.querySelector('.modal-close').onclick=()=>actionModal.close();actionModal.addEventListener('click',e=>{if(e.target===actionModal)actionModal.close()});document.querySelectorAll('[data-open-modal]').forEach(b=>b.onclick=()=>{const dealer=b.dataset.openModal==='dealer';modalContent.innerHTML=`<h2 class="modal-title">${dealer?'Join the founding dealer network':'Create a price alert'}</h2><p class="modal-copy">${dealer?'List inventory, configure pricing and receive qualified local demand.':'Get notified when your selected metal reaches your target price.'}</p><form class="modal-form"><input required placeholder="${dealer?'Business name':'Target price'}"><input required type="email" placeholder="Email address"><button class="primary-btn" style="padding:14px">${dealer?'Request early access':'Create alert'}</button></form>`;modalContent.querySelector('form').onsubmit=e=>{e.preventDefault();modalContent.innerHTML='<div class="success">✓ Prototype submission captured. No information was sent or stored.</div>'};actionModal.showModal()});render();
